version: "3"
services:
  nodejs-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      NEXT_PUBLIC_API_BASE_URL_V2: ${NEXT_PUBLIC_API_BASE_URL_V2}
